import "./globals.css";
import Link from "next/link";

import NavTop from "./components/NavTop";
import NavLeft from "./components/NavLeft";
import NavBottom from "./components/NavBottom";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <body>
        <div className="app">
          <NavLeft />
          <NavTop />
          <main className="main">{children}</main>
          <NavBottom />
        </div>
      </body>
    </html>
  );
}
